/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.eduk.kafka.confirmation.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum ConfirmationApprovalStatus implements org.apache.avro.generic.GenericEnumSymbol<ConfirmationApprovalStatus> {
  APPROVED, REJECTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ConfirmationApprovalStatus\",\"namespace\":\"com.eduk.kafka.confirmation.avro.model\",\"symbols\":[\"APPROVED\",\"REJECTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
